<?php

namespace AppBundle\Repository;

/**
 * CursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefonoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getContacto($id_contacto) {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT id
            FROM telefono
            WHERE contacto_id = :price';
        $stmt = $conn->prepare($sql);   
        $stmt->execute(['price' => $id_contacto]);

        // $telefono_id = $query->getResult();

        return $stmt->fetchColumn();
    }
}
