agenda_index:
    path: /
    defaults: { _controller: AppBundle:Contacto:new }


# Rutas para los contactos
all_contactos:
    path: /contactos
    defaults: { _controller: AppBundle:Contacto:viewAll }

view_contacto:
    path: /view/{id}
    defaults: { _controller: AppBundle:Contacto:view }

add_contacto:
    path: /add
    defaults: { _controller: AppBundle:Contacto:add }

edit_contacto:
    path: /edit/{id}
    defaults: { _controller: AppBundle:Contacto:edit }

delete_contacto:
    path: /delete/{id}
    defaults: { _controller: AppBundle:Contacto:delete }

# Rutas para etiquetas
all_etiquetas:
    path: /etiquetas
    defaults: { _controller: AppBundle:Etiqueta:viewAll }

add_etiqueta:
    path: /etiquetas/add
    defaults: { _controller: AppBundle:Etiqueta:add }

edit_etiqueta:
    path: /etiquetas/edit/{id}
    defaults: { _controller: AppBundle:Etiqueta:edit }

delete_etiqueta:
    path: /etiquetas/delete/{id}
    defaults: { _controller: AppBundle:Etiqueta:delete }