AppBundle\Entity\Contacto:
    type: entity
    table: contacto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    oneToMany:
        telefono:
                targetEntity: Telefono
                mappedBy: contacto
                cascade: [persist]
    lifecycleCallbacks: {  }
